services:
  web:
    image: nginx
    ports:
      - 81:80
    volumes:
      - /home/badma/projects/my-environment/docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - /home/badma/projects/my-environment:/var/www/html

  php-fpm:
    build: ./docker/php
    volumes:
      - /home/badma/projects/my-environment:/var/www/html

  postgres_db:
    image: postgres:13
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 54324:5432